backend:
  name: git-gateway
  branch: new-netlify-cms

media_folder: static/img
public_folder: /img

collections:
  - name: "brand"
    label: "Brand"
    folder: "src/pages/brands"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "brand"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Logo", name: "logo", widget: "image"}
      - label: Products
        name: products
        widget: list
        fields:
          - {label: Photo, name: photo, widget: image }
          - {label: Name, name: name, widget: string}
          - {label: Sold, name: sold, widget: number, valueType: int}
          - {label: Target, name: target, widget: number, valueType: int}
          - {label: Category, name: category, widget: select, options: ["Trending", "High Profitability", "On Sale", "Missing Inventory"]}
      - name: "tasks"
        label: "Tasks"
        widget: "list"
        fields: 
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Type", name: "type", widget: "select", options: ["improve", "trend", "pair"]}
          - {label: "Done", name: "done", widget: "boolean", default: true}
          - {label: "Badge", name: "badge", widget: "select", options: ["trending", "instagram", "pair", "bestSeller"]}
          - {label: "Path", name: "path", widget: "string"}
          - {label: "id", name: "ID", widget: "string"}
      - name: "categories"
        label: "Categories"
        widget: "list"
        fields: 
          - {label: "Name", name: "name", widget: "string"}
          - {label: "ID", name: "id", widget: "string"}
          - {label: "Position", name: "position", widget: "number", default: 0, valueType: "int"}
       

         