backend:
  name: git-gateway
  branch: new-netlify-cms

media_folder: static/img
public_folder: /img

collections:
  - name: "brand"
    label: "Brand"
    folder: "src/pages/brands"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "brand"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Logo", name: "logo", widget: "image"}
      - name: feedPage
        label: Feed Page
        widget: object
        fields: 
          - name: products
            label: Products 
            widget: list
            fields: 
              - {label: Title, name: title, widget: string }
              - {label: ID, name: id, widget: string}
              - {label: Image, name: image, widget: image}
              - {label: Badge, name: badge, widget: select, options: ["trending", "instagram", "pair", "bestSeller"]}
              - {label: Badge Title, name: badgeTitle, widget: string}
      - label: Products
        name: products
        widget: list
        fields:
          - {label: Title, name: title, widget: string }
          - {label: ID, name: id, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Badge, name: badge, widget: select, options: ["trending", "instagram", "pair", "bestSeller"]}
          - {label: Badge Title, name: badgeTitle, widget: string}
      - name: "tasks"
        label: "Tasks"
        widget: "list"
        fields: 
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Type", name: "type", widget: "select", options: ["improve", "trend", "pair"]}
          - {label: "Done", name: "done", widget: "boolean", default: true}
          - {label: "Badge", name: "badge", widget: "select", options: ["trending", "instagram", "pair", "bestSeller"]}
          - {label: "Path", name: "path", widget: "string"}
          - {label: "id", name: "ID", widget: "string"}
      - name: "categories"
        label: "Categories"
        widget: "list"
        fields: 
          - {label: "Name", name: "name", widget: "string"}
          - {label: "ID", name: "id", widget: "select", options: ["trending", "new", "missing", "bestSeller", "onSale"]}
          - {label: "Position", name: "position", widget: "number", default: 0, valueType: "int"}
       

         